// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// Logged during the processing of an event published to a message bus.
public struct MessageBusActivity: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The unique system generated ID when a message bus receives an event. This
  /// ID is propagated throughout the request.
  public var messageUid: Swift.String = Swift.String()

  /// The CloudEvent ID and source from the attributes of the event.
  public var attributes: [Swift.String: Swift.String] = [:]

  /// The point in time when the activity occurred.
  public var activityTime: GoogleCloudWkt.Timestamp? = nil

  /// One of the activities that can be logged during the processing of an event
  /// published to a message bus.
  public var activity: OneOf_Activity? = nil

  /// Initialize a new instance of `MessageBusActivity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MessageBusActivity().with { $0.messageUid = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case messageUid = "messageUid"
    case attributes = "attributes"
    case activityTime = "activityTime"
    case received = "received"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.messageUid = try container.decode(Swift.String.self, forKey: .messageUid)
    self.attributes = try container.decode([Swift.String: Swift.String].self, forKey: .attributes)
    self.activityTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .activityTime)

    var activity: OneOf_Activity? = nil
    let activityCheckAndSet = {
      if activity != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'activity'"))
      }
      activity = $0
    }
    if let received = try container.decodeIfPresent(
      MessageBusActivity.Received?.self, forKey: .received)
    {
      try activityCheckAndSet(.received(received))
    }
    self.activity = activity
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.messageUid, forKey: .messageUid)
    try container.encode(self.attributes, forKey: .attributes)
    try container.encode(self.activityTime, forKey: .activityTime)

    if let choice = self.activity {
      switch choice {
      case .received(let value):
        try container.encode(value, forKey: .received)
      }
    }
  }

  /// Structured log message that is emitted when an event is received by a
  /// message bus.
  public struct Received: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Informational details about the event received.
    public var details: Swift.String = Swift.String()

    /// Logged when the enrollment encounters an error.
    public var error: GoogleRpc.Status? = nil

    /// Initialize a new instance of `Received`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Received().with { $0.details = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.eventarc.logging.v1.MessageBusActivity.Received"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// One of the activities that can be logged during the processing of an event
  /// published to a message bus.
  public enum OneOf_Activity: Codable, Equatable, Sendable {
    /// Logged when an event is received by a message bus.
    indirect case received(MessageBusActivity.Received?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.logging.v1.MessageBusActivity"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
