// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// Logged during the processing of a message in a pipeline.
public struct PipelineActivity: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The unique system generated ID associated with the event passed from the
  /// message bus.
  public var messageUid: Swift.String = Swift.String()

  /// The CloudEvent ID and source from the attributes of the event.
  public var attributes: [Swift.String: Swift.String] = [:]

  /// The point in time when the activity occurred.
  public var activityTime: GoogleCloudWkt.Timestamp? = nil

  /// Oneof for the different logging activities in a pipeline.
  public var activity: OneOf_Activity? = nil

  /// Initialize a new instance of `PipelineActivity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PipelineActivity().with { $0.messageUid = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case messageUid = "messageUid"
    case attributes = "attributes"
    case activityTime = "activityTime"
    case messageReceived = "messageReceived"
    case messageTransformed = "messageTransformed"
    case messageConverted = "messageConverted"
    case messageRequestDispatched = "messageRequestDispatched"
    case messageResponseReceived = "messageResponseReceived"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.messageUid = try container.decode(Swift.String.self, forKey: .messageUid)
    self.attributes = try container.decode([Swift.String: Swift.String].self, forKey: .attributes)
    self.activityTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .activityTime)

    var activity: OneOf_Activity? = nil
    let activityCheckAndSet = {
      if activity != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'activity'"))
      }
      activity = $0
    }
    if let messageReceived = try container.decodeIfPresent(
      PipelineActivity.MessageReceived?.self, forKey: .messageReceived)
    {
      try activityCheckAndSet(.messageReceived(messageReceived))
    }
    if let messageTransformed = try container.decodeIfPresent(
      PipelineActivity.MessageTransformed?.self, forKey: .messageTransformed)
    {
      try activityCheckAndSet(.messageTransformed(messageTransformed))
    }
    if let messageConverted = try container.decodeIfPresent(
      PipelineActivity.MessageConverted?.self, forKey: .messageConverted)
    {
      try activityCheckAndSet(.messageConverted(messageConverted))
    }
    if let messageRequestDispatched = try container.decodeIfPresent(
      PipelineActivity.MessageRequestDispatched?.self, forKey: .messageRequestDispatched)
    {
      try activityCheckAndSet(.messageRequestDispatched(messageRequestDispatched))
    }
    if let messageResponseReceived = try container.decodeIfPresent(
      PipelineActivity.MessageResponseReceived?.self, forKey: .messageResponseReceived)
    {
      try activityCheckAndSet(.messageResponseReceived(messageResponseReceived))
    }
    self.activity = activity
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.messageUid, forKey: .messageUid)
    try container.encode(self.attributes, forKey: .attributes)
    try container.encode(self.activityTime, forKey: .activityTime)

    if let choice = self.activity {
      switch choice {
      case .messageReceived(let value):
        try container.encode(value, forKey: .messageReceived)
      case .messageTransformed(let value):
        try container.encode(value, forKey: .messageTransformed)
      case .messageConverted(let value):
        try container.encode(value, forKey: .messageConverted)
      case .messageRequestDispatched(let value):
        try container.encode(value, forKey: .messageRequestDispatched)
      case .messageResponseReceived(let value):
        try container.encode(value, forKey: .messageResponseReceived)
      }
    }
  }

  /// Structured log that is emitted when a message is received in this Pipeline
  /// (or an error encountered).
  public struct MessageReceived: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Informational details when a message is received from a source.
    public var details: Swift.String = Swift.String()

    /// Input payload format of the message.
    public var inputPayloadFormat: PipelineActivity.PayloadFormat = PipelineActivity.PayloadFormat()

    /// Error encountered when receiving a message from a Channel, or if the
    /// message is malformed.
    public var error: GoogleRpc.Status? = nil

    /// Initialize a new instance of `MessageReceived`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MessageReceived().with { $0.details = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.eventarc.logging.v1.PipelineActivity.MessageReceived"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Structured log that is emitted when a message is transformed during
  /// mediation (or an error encountered) in a Pipeline.
  public struct MessageTransformed: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Informational details when a message is transformed during mediation.
    public var details: Swift.String = Swift.String()

    /// Error encountered when transforming a message.
    public var error: GoogleRpc.Status? = nil

    /// Initialize a new instance of `MessageTransformed`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MessageTransformed().with { $0.details = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.eventarc.logging.v1.PipelineActivity.MessageTransformed"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Structured log that is emitted when a message is converted during
  /// mediation (or an error encountered) in a Pipeline.
  public struct MessageConverted: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Informational details when a message is converted during mediation.
    public var details: Swift.String = Swift.String()

    /// Input payload format of the message.
    public var inputPayloadFormat: PipelineActivity.PayloadFormat = PipelineActivity.PayloadFormat()

    /// Output payload format of the message.
    public var outputPayloadFormat: PipelineActivity.PayloadFormat =
      PipelineActivity.PayloadFormat()

    /// Error encountered when converting a message.
    public var error: GoogleRpc.Status? = nil

    /// Initialize a new instance of `MessageConverted`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MessageConverted().with { $0.details = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.eventarc.logging.v1.PipelineActivity.MessageConverted"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Structured log that is emitted when a message request is dispatched to a
  /// destination (or an error encountered) in a Pipeline.
  public struct MessageRequestDispatched: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Informational details when a message is dispatched to a destination.
    public var details: Swift.String = Swift.String()

    /// The destination where the event is sent to.
    public var destination: Swift.String = Swift.String()

    /// Error encountered before dispatching a message, e.g., malformed
    /// destination.
    public var error: GoogleRpc.Status? = nil

    /// Initialize a new instance of `MessageRequestDispatched`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MessageRequestDispatched().with { $0.details = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.eventarc.logging.v1.PipelineActivity.MessageRequestDispatched"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Structured log that is emitted when a message response (or error) is
  /// received from a destination for a message request that was dispatched
  /// earlier in a Pipeline.
  public struct MessageResponseReceived: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Informational details when a message response was received by the target,
    /// or when the request failed.
    public var details: Swift.String = Swift.String()

    /// The retry decision for the message after the response is received.
    public var retryStatus: PipelineActivity.MessageResponseReceived.RetryStatus = PipelineActivity
      .MessageResponseReceived.RetryStatus()

    /// The future time when the message request will be retried. Present if and
    /// only if the `retry_status` is `WILL_RETRY`.
    public var retryTime: GoogleCloudWkt.Timestamp? = nil

    /// The HTTP response code received with the message response.
    public var httpResponseCode: Swift.Int32 = Swift.Int32()

    /// Status of the message response received.
    public var error: GoogleRpc.Status? = nil

    /// Initialize a new instance of `MessageResponseReceived`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MessageResponseReceived().with { $0.details = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Enum to encode the retry decision for the message after the response is
    /// received.
    public enum RetryStatus: Codable, Equatable, Sendable {
      /// Default value. This value is unused.
      case unspecified
      /// The Pipeline will retry dispatching the message to the destination.
      case willRetry
      /// The Pipeline will not retry this message anymore.
      case retryExhausted
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .willRetry: return 1
        case .retryExhausted: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "RETRY_STATUS_UNSPECIFIED"
        case .willRetry: return "WILL_RETRY"
        case .retryExhausted: return "RETRY_EXHAUSTED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RetryStatus/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "RETRY_STATUS_UNSPECIFIED": self = .unspecified
        case "WILL_RETRY": self = .willRetry
        case "RETRY_EXHAUSTED": self = .retryExhausted
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RetryStatus/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .willRetry
        case 2: self = .retryExhausted
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .willRetry: return try container.encode(1)
        case .retryExhausted: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.eventarc.logging.v1.PipelineActivity.MessageResponseReceived"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Format of the payload.
  public enum PayloadFormat: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// JSON payload format.
    case json
    /// Proto payload format.
    case proto
    /// Avro payload format.
    case avro
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .json: return 1
      case .proto: return 2
      case .avro: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PAYLOAD_FORMAT_UNSPECIFIED"
      case .json: return "JSON"
      case .proto: return "PROTO"
      case .avro: return "AVRO"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PayloadFormat/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PAYLOAD_FORMAT_UNSPECIFIED": self = .unspecified
      case "JSON": self = .json
      case "PROTO": self = .proto
      case "AVRO": self = .avro
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PayloadFormat/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .json
      case 2: self = .proto
      case 3: self = .avro
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .json: return try container.encode(1)
      case .proto: return try container.encode(2)
      case .avro: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Oneof for the different logging activities in a pipeline.
  public enum OneOf_Activity: Codable, Equatable, Sendable {
    /// Logging when a message is received in this Pipeline (or an error
    /// encountered).
    indirect case messageReceived(PipelineActivity.MessageReceived?)
    /// Logging when a message is transformed during mediation (or an error
    /// encountered).
    indirect case messageTransformed(PipelineActivity.MessageTransformed?)
    /// Logging when a message is converted during mediation (or an error
    /// encountered).
    indirect case messageConverted(PipelineActivity.MessageConverted?)
    /// Logging when a message request is dispatched to a destination (or an
    /// error encountered).
    indirect case messageRequestDispatched(PipelineActivity.MessageRequestDispatched?)
    /// Logging when a message response (or error) is received from a
    /// destination.
    indirect case messageResponseReceived(PipelineActivity.MessageResponseReceived?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.logging.v1.PipelineActivity"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
